Making the imports

In [ ]:

import numpy as np #so as to make our calculations easy
import pandas as pd #to read our input data 


Exploring the Data:

In [ ]:
from sklearn.datasets dataset import pd.read_csv('/content/sample_data/Churn_Modelling.csv')    #where sklearn is the framework of Machine learning 
                                         #load_iris is the function so induced 
churn_modeilling_datasets = load_churn_modeilling()               #It's the name of the dataset
data = load_churn_modeilling()

SyntaxError: ignored

In [ ]:
print("Keys of iris_datasets: \n{}" .format(iris_datasets.keys()))  #loaded data is in form of dictionary 


print(iris_datasets['DESCR'][:193] + "\n...")  #calling the dictionary, here DESCR is the key

                                             


Keys of iris_datasets: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
...


 List of strings, where each string represents the species in the dataset:

In [ ]:
val= iris_datasets['DESCR']  #Using key "DESCR" - description of the flower from the dataset
start_val=val[:200]
print( start_val + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive
...


Using the key "target name" 

In [ ]:
print("Target names:  {}".format(iris_datasets['target_names']))

Target names:  ['setosa' 'versicolor' 'virginica']


Using the key "Feature name" , it contains the 'sepal length','sepal width',petal length','petal width'

In [ ]:
print("Feature names: \n{}".format(iris_datasets['feature_names']))

Feature names: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


Testification of the type of Data: Whether it's a list, tuple etc. 

In [ ]:
print("Type of Data: {}".format(type(iris_datasets['data'])))

Type of Data: <class 'numpy.ndarray'>


Testification of the shape(matrix based on the dataset)

In [ ]:
print("Shape of Data: {}".format(iris_datasets['data'].shape))  #150 rows/150 instances of flowers(50 instances of each)
                                                                #4 columns /4 attributes 

Shape of Data: (150, 4)


In [ ]:
print("First five columns of data:\n{}".format(iris_datasets['data'][:5]))  #using slicing 

First five columns of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


Introduction to numPy array: that is, the last key array containing the species of each of the flowers that were measured and it also has a numPy array..

In [ ]:
print("Types of target: {}".format(type(iris_datasets['target'])))

Types of target: <class 'numpy.ndarray'>


Target is the 1D array, now inducing the shape: 

In [ ]:
print("Shape of target: {}".format(iris_datasets['target'].shape))

Shape of target: (150,)


Exploring more with the target and the shape: 

In [ ]:
print("Target:\n{}".format(iris_datasets['target']))

Target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


Now, splitting  the training and testing data:

In [ ]:
from sklearn.model_selection import train_test_split  #train_test_split is the function used to split the data into by default(75% and 25%) traing and testing parts
X_train,X_test,y_train,y_test = train_test_split(     #4 variables used where X stands for features/attributes of the width, length of the petal and sepal accordingly 
                                                      #y stands for the labels( 3 categories)
                                                      #train_test_split, it returns the tuples
    iris_datasets['data'],iris_datasets['target'], random_state=0  #random_state = all rows are arranged in a similar manner/rearrangement manner
)     #PEP guidelinresss in python intacted. 

NP array part: 

In [ ]:
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))
print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))

X_train shape: (112, 4)
y_train shape: (112,)
X_test shape: (38, 4)
y_test shape: (38,)


Now, making the model of K -Nearest neighbors : 

---



In [ ]:
from sklearn.neighbors import KNeighborsClassifier  #name of the model is KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)           #value of k= n_neighbor= 1

Training the model on the trained data : 

In [ ]:
knn.fit(X_train,y_train) #knn.fit is the function or attribute of the knn classifier
                         #arguments passed in the brackets 

NameError: ignored

Ending of the training part!

Predictions: Testing on the a single datapoint from the dataset. 

In [ ]:
X_new=np.array([[5,2.9,1,0.2]])   #2 dimensional datapoint passed, alas double paranthesis 
print("X_new.shape: {}".format(X_new.shape))

X_new.shape: (1, 4)


In [ ]:
prediction = knn.predict(X_new)
print("Prediction: {}".format(prediction))
print("Predicted target name: {}".format(iris_datasets['target_names'][prediction]))



Prediction: [0]
Predicted target name: ['setosa']


Evaluating section: 
Now, testing is done on the tested dataset: 

In [ ]:
y_pred = knn.predict(X_test) #y_pred stands for the predicted values of y of the model 
                             #X_test : 2D NDarray
print("Test set predictions: \n{}".format(y_pred))

Test set predictions: 
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


To check whether the predicted values is correct or wrong: 

In [ ]:
print("Test set score: {}".format(np.mean(y_pred == y_test)))  #y_pred = model values of data point
                                                               #y_test = actual values of test dataset 
                                                               #if y_pred == y_test then, 1(true) else 0(false)
                                                               #final output would give the accuracy of the model 


Test set score: 0.9736842105263158
